### ISSUE TITLE
Edit text size for panel labels?

### ISSUE THREAD

**Issue by CyclingNut27** [jimjam-slam/stickylabeller#8]
Hi there -- I am using this package to annotate my panel labels for a figure I have targeted for publication. I really love the package and was able to annotate the labels as I desired. However, the base size of the text for the labels appears too small in the final figure. Is there any way to increase the font size for the labels? If not, can you please add it? 

Sincerely,
Augustus

**Comment by jimjam-slam** [comment]
Hi there! You can make the facet strip text bigger native with ggplot2. Use the `strip.text` argument of the [`theme` function](https://ggplot2.tidyverse.org/reference/theme.html).

Try, for example, `strip.text = element_text(size = rel(1.5))`.

**Comment by CyclingNut27** [comment]
Thanks for getting back to me so quickly!

I believe I tried that once before with no success... But I will try it
again this evening and get back to you.

Much appreciated!
- Gus

**Comment by CyclingNut27** [comment]
Hi there,

Sorry for the delay in reply. I tried the code you suggested with my ggplot, and it unfortunately did not work. Here is the code I used, specifically:

my.cols = c("#F8F9F9","#7F8C8D")
my.cols

Infection.boxplot2 = ggplot(data = Kudoa.grouped, aes(x=Sex, y = Infection, fill = Sex)) + 
  geom_boxplot() +
  facet_wrap(~Age, labeller = label_glue('({.l}) Age = {Age} yr')) +  theme(strip.text = element_text(size = rel(1.5))) +
  scale_fill_manual(values = my.cols) + 
  scale_y_log10(breaks = trans_breaks("log10", function(x) 10^x),
              labels = trans_format("log10", math_format(10^.x))) +
  scale_x_discrete(name = "Sex", labels =c("1" = "Male", "2" = "Female")) +
  ylab("Myxospore Density (# spores /g)")

p2 = Infection.boxplot2 + theme_Publication() +theme(legend.position = "none")
p2

**Comment by jimjam-slam** [comment]
I'm just getting home from a trip today, so I'll try to reproduce this tomorrow!

**Comment by jimjam-slam** [comment]
Here's the example from the README modified to test `strip.text`, and it works for me:

```r
library(tibble)
library(ggplot2)
library(stickylabeller)

mydf <- tibble(
  x = 1:90,
  y = rnorm(90),
  red = rep(letters[1:3], 30),
  blue = c(rep(1, 30), rep(2, 30), rep(3, 30)))
```

```r
p1 <- ggplot(mydf) +
  geom_point(aes(x = x, y = y)) +
  facet_wrap(
  vars(red, blue),
  labeller = label_glue('Red is {red}\nand blue is {blue}'))
```

```r
p1
```

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/6520659/175186940-6de9d0b1-2ee0-4b6d-a6c0-e3a1f1b2472c.png">

```r
p1 + theme(strip.text = element_text(size = rel(1.5)))
```

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/6520659/175187253-69b0d088-0c6e-4358-b5d3-f3bbb234db4c.png">

One possibility with your example is that `p2` includes an additional `theme_*` call. Depending on how it's defined, this theme could be overriding the `strip.text` sizing.  How does `Infection.boxplot2` look?

**Comment by CyclingNut27** [comment]
Thanks so much! I managed to get it to work as well -- I simply had another
theme() argument that was overriding the strip.text(size = rel(1.5)) call.

I really appreciate the help!

**Comment by jimjam-slam** [comment]
I'm glad to hear it! 😊
